version: '3.8'

services:
  web:
    build: .
    image: gemini-form-app
    container_name: gemini-form-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run build:scss && python app.py"
    working_dir: /app
